### ISSUE TITLE
question!

### ISSUE THREAD

**Issue by nices0325** [Brentem-School/Elmduino-Emulator#1]
How can I run it??

**Comment by Brentem** [comment]
If you downloaded the repository, you click on Elmduino Emulator.sln to open it in visual studio. If you are in visual studio you press the start/debug button.

**Comment by Brentem** [comment]
I have added extra information to the README if this helped you let me know so that I can close this issue.

**Comment by nices0325** [comment]
> 이 문제를 해결할 수 있도록 알려주는 데 도움이된다면 README에 추가 ​​정보를 추가했습니다.

I'm gonna test it soon. Thanks for your kind answer~!

**Comment by nices0325** [comment]
doesn't it work on m1 mac? It occurs mono64 error..

**Comment by Brentem** [comment]
No it doesn't work on m1 mac yet, because it's made in .NET Framework 4.7.2. Maybe in the future I can try to port it to .NET 5.0 and then it should work for m1 mac as well.

**Comment by nices0325** [comment]
> 아니요. .NET Framework 4.7.2로 제작 되었기 때문에 m1 mac에서는 아직 작동하지 않습니다. 아마도 장래에 .NET 5.0으로 포팅을 시도 할 수 있으며 m1 mac에서도 작동 할 것입니다.

I'm looking forward to see .NET5.0 version... when will be released??

**Comment by Brentem** [comment]
I have just ported to .NET 5.0 what happens now when you download the source code and run it?

**Comment by nices0325** [comment]
> 방금 .NET 5.0으로 이식했습니다. 소스 코드를 다운로드하고 실행하면 어떻게됩니까?

It occurs error
compiler box says that 'NuGet should be restored' but It can not be done..

**Comment by Brentem** [comment]
Yes it can not be done, because this application is a Windows Forms app so it only works on windows, despite that .NET 5.0 is multi platform I just found this out. In the future I will put more research into cross platform. I will close this issue with this comment.

**Comment by nices0325** [comment]
> Yes it can not be done, because this application is a Windows Forms app so it only works on windows, despite that .NET 5.0 is multi platform I just found this out. In the future I will put more research into cross platform. I will close this issue with this comment.

Do appreciate for your reply! I'm waiting for cross platform!
